spring:
  application:
    name: order-api

  profiles:
    active: dev
  jpa:
    open-in-view: false


  rabbitmq:
    username: admin
    password: nhnacademy123!
    host: 133.186.241.167
    port: 5672

logging:
  config: classpath:logback-spring.xml

payment:
  toss:
    test_widget_api_key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    test_secret_api_key: test_sk_BX7zk2yd8yj65jD6b9Yv3x9POLqK

app:
  initialize: true

api:
  tracking:
    key: wmkoSaNXvX41qbzwSp2KzQ


management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

url: https://api-keymanager.nhncloudservice.com
appKey: qTQNj7LyHhdAazH3
keyId: f5e65a4f86194461bb3b6a01de675dcf