spring:
  application:
    name: order-api

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-total: 50   # 50~200
      max-idle: 30
      min-idle: 10
      test-on-borrow: true
      validation-query: SELECT 1
      remove-abandoned-on-borrow: true

  rabbitmq:
    username: admin
    password: nhnacademy123!
    host: 133.186.241.167
    port: 5672

logging:
  config: classpath:logback-spring.xml