server:
  port: 8088
  shutdown: graceful

spring:
#  datasource:
#    url: jdbc:mysql://133.186.241.167:3306/triple_seven_order?serverTimezone=UTC&characterEncoding=UTF-8
#    username: triple_seven
#    password: eo1cItEUe@J2Tym
#    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 225
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
    open-in-view: false

  rabbitmq:
    virtual-host: vh1_prod

  lifecycle:
    timeout-per-shutdown-phase: 30s


management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka
  instance:
    instance-id: order-api-1
    hostname: localhost
    prefer-ip-address: true