server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
#    상황에 따라 eureka 설정
    enabled: true
  instance:
    instance-id: order-api
    hostname: localhost
    prefer-ip-address: true


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    virtual-host: vh1_dev


