server:
  port: 8088

eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 14782454k!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
                   # 유휴 커넥션에 대해 유효성 검사
    dbcp2:
      initial-size: 5   # 초기 커넥션 풀 크기
      max-total: 10     # 최대 커넥션 풀 크기
      max-idle: 5       # 최대 유휴 커넥션 수
      min-idle: 2       # 최소 유휴 커넥션 수
      validation-query: SELECT 1  # 커넥션 유효성 검사 쿼리
      test-on-borrow: true        # 커넥션을 빌릴 때 유효성 검사
      test-while-idle: true       # 유휴 커넥션에 대해 유효성 검사

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    defer-datasource-initialization: true



  #spring:
#  datasource:
#    url: jdbc:h2:mem:devDB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  output:
#    ansi:
#      enabled: always
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  web:
#    resources:
#      add-mappings: false
#  sql:
#    init:
#      mode: always


  # Swagger springdoc-ui Configuration
  springdoc:
    packages-to-scan: com.example.orderapi
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    cache:
      disabled: true              # 캐시 사용 여부
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    swagger-ui:
      enabled: true               # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8080/swagger-ui/index.html>
      path: /order-api.html         # Swagger UI 추가 접근 경로 => <http://localhost:8080/demo-ui.html>
      tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
      operations-sorter: alpha    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  jmx:
    enabled: true


