spring:
  application:
    name: order-api
  profiles:
    active: dev
  jpa:
    open-in-view: false

logging:
  config: classpath:logback-spring.xml


payment:
  toss:
    test_client_api_key: test_ck_BX7zk2yd8yJlqyeZoOmL3x9POLqK
    test_secret_api_key: test_sk_BX7zk2yd8yj65jD6b9Yv3x9POLqK


