spring:
  application:
    name: order-api

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-total: 50   # 50~200
      max-idle: 30
      min-idle: 10
      test-on-borrow: true
      validation-query: SELECT 1
      remove-abandoned-on-borrow: true

  rabbitmq:
    username: admin
    password: nhnacademy123!
    host: 133.186.241.167
    port: 5672

logging:
  config: classpath:logback-spring.xml

payment:
  toss:
    test_client_api_key: test_ck_BX7zk2yd8yJlqyeZoOmL3x9POLqK
    test_secret_api_key: test_sk_BX7zk2yd8yj65jD6b9Yv3x9POLqK

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.example.orderapi
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true              # 캐시 사용 여부
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true               # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8080/swagger-ui/index.html>
    path: /order-api.html         # Swagger UI 추가 접근 경로 => <http://localhost:8080/demo-ui.html>
    tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
