server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    instance-id: order-api
    hostname: localhost
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  rabbitmq:
    virtual-host: vh1_dev

#spring:
#  datasource:
#    url: jdbc:h2:mem:devDB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  output:
#    ansi:
#      enabled: always
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  web:
#    resources:
#      add-mappings: false
#  sql:
#    init:
#      mode: always


