server:
  port: 8088

eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:devDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

  web:
    resources:
      add-mappings: false
  sql:
    init:
      mode: always


