server:
  port: 8089
  shutdown: graceful

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka
  instance:
    instance-id: order-api
    hostname: localhost
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team3_order?serverTimezone=UTC&characterEncoding=UTF-8
    username: triple_seven
    password: eo1cItEUe@J2Tym
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  rabbitmq:
    virtual-host: vh1_prod

  lifecycle:
    timeout-per-shutdown-phase: 30s

