server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/
#    상황에 따라 eureka 설정
    enabled: true
  instance:
    health-check-url: /actuator/health
    instance-id: order-api
    hostname: localhost
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_order?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate.format_sql: true

  rabbitmq:
    virtual-host: vh1_dev
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0



