server:
  port: 8089
  shutdown: graceful

spring:
#  datasource:
#    url: jdbc:mysql://133.186.241.167:3306/triple_seven_order?serverTimezone=UTC&characterEncoding=UTF-8
#    username: triple_seven
#    password: eo1cItEUe@J2Tym
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
    open-in-view: false

  rabbitmq:
    virtual-host: vh1_prod

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-total: 50   # 50~200
      max-idle: 30
      min-idle: 10
      test-on-borrow: true
      validation-query: SELECT 1
      remove-abandoned-on-borrow: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka
  instance:
    instance-id: order-api-2
    hostname: localhost
    prefer-ip-address: true

url: https://api-keymanager.nhncloudservice.com
appKey: qTQNj7LyHhdAazH3
keyId: 22611337ca804b778ddf7b036c824807
keyStoreFilePath: triple-seven.p12
password: nhn24

