name: CI/CD Pipeline for Spring Boot Order Api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set File Permissions
        run: chmod 644 toast-logncrash-logback-sdk-3.0.5.jar
        
      - name: List files for debugging
        run: ls -al libs

      
      - name: Install LogNCrash With Maven
        run: | 
            mvn install:install-file \            
            -Dfile=libs/toast-logncrash-logback-sdk-3.0.5.jar \
            -DgroupId=com.toast.java.logncrash \
            -DartifactId=logncrash-logback-sdk \
            -Dversion=3.0.5 \
            -Dpackaging=jar

          
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=tripleseven-order-api \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t lushlife99/nhn-order:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Remove unused Docker images
        run: |
          docker image prune -a --filter "until=72h"
        
      - name: Push Docker image
        run: |
          docker push lushlife99/nhn-order:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to First Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull lushlife99/nhn-order:${{ github.sha }}
            if [ "$(docker ps -aq --filter "name=order-api-instance-1")" ]; then
              docker stop order-api-instance-1 || true
              docker rm -f order-api-instance-1 || true
            fi
              docker run --name order-api-instance-1 --network nhn-book-store-network -p 8088:8088 -e SPRING_PROFILES_ACTIVE=instance1 -d lushlife99/nhn-order:${{ github.sha }}



      - name: Deploy to Second Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ "$(docker ps -aq --filter "name=order-api-instance-2")" ]; then
              docker stop order-api-instance-2 || true
              docker rm -f order-api-instance-2 || true
            fi
              docker run --name order-api-instance-2 --network nhn-book-store-network -p 8089:8089 -e SPRING_PROFILES_ACTIVE=instance2 -d lushlife99/nhn-order:${{ github.sha }}
